### ISSUE TITLE
一周观剧记录 | flipped的个人博客

### ISSUE THREAD

**Issue by qiangzhang0925** [qiangzhang0925/images#2]
https://qiangzhang0925.github.io/2020/08/14/%E4%B8%80%E5%91%A8%E8%A7%82%E5%89%A7%E8%AE%B0%E5%BD%95/ 

 重启之极海听雷第一季(完结)

**Comment by qiangzhang0925** [comment]
欢迎大家积极评论啊

**Comment by jixiaw** [comment]
强哥可以啊，半泽直树好看

**Comment by qiangzhang0925** [comment]
> @qiangzhang0925
> 欢迎大家积极评论啊


> @jixw123
> 强哥可以啊，半泽直树好看
看到pyq很多人在看，将就准备看一下
